### ISSUE TITLE
Documentation doesn't match config file

### ISSUE THREAD

**Issue by mpfl** [ourresearch/software-mentions#20]
I've been playing around with software-mentions with some success. I'd like to use the scibert fine-tuned model, but the documentation doesn't match what appears in the config.yaml file.

The documentation says to use:

```yaml
model:
  name: "software"
  engine: "delft"
  delft:  
    architecture: "scibert"
```

But the config file contains a `models:` section. I've tried:

1. Removing the `models:` section entirely and replacing it with what's in the documentation.
2. Leaving all models intact but changing only "software" to use scibert.
3. Changing all models to use scibert.

In all cases I get errors saying the model can't be loaded.

**Comment by kermitt2** [comment]
Hi @mpfl 

Thanks for the issue. 

Indeed the name of the base tranformer model needs to be indicated in the config. file in the latest version, I update the documentation right now. The line `transformer: "allenai/scibert_scivocab_cased"` need to be added for the models in the config under the `deflt:` block. 

For example, my config file with all the scibert fine tuned models (the ones automatically donwloaded with `./gradlew installScibert`) is as folllow:

```
models:
  - name: "software"
    #engine: "wapiti"
    engine: "delft"
    wapiti:
      # wapiti training parameters, they will be used at training time only
      epsilon: 0.00001
      window: 30
      nbMaxIterations: 1500
    delft:
      # deep learning parameters
      #architecture: "BidLSTM_CRF"
      #useELMo: false
      #embeddings_name: "glove-840B"
      architecture: "BERT_CRF"
      transformer: "allenai/scibert_scivocab_cased"

  - name: "software_context"
    engine: "delft"
    delft:
      #architecture: "gru"
      #embeddings_name: "glove-840B"
      architecture: "bert"
      transformer: "allenai/scibert_scivocab_cased"

  - name: "software_context_used"
    engine: "delft"
    delft:
      #architecture: "gru"
      #embeddings_name: "glove-840B"
      architecture: "bert"
      transformer: "allenai/scibert_scivocab_cased"

  - name: "software_context_creation"
    engine: "delft"
    delft:
      #architecture: "gru"
      #embeddings_name: "glove-840B"
      architecture: "bert"
      transformer: "allenai/scibert_scivocab_cased"

  - name: "software_context_shared"
    engine: "delft"
    delft:
      #architecture: "gru"
      #embeddings_name: "glove-840B"
      architecture: "bert"
      transformer: "allenai/scibert_scivocab_cased"
```

Also note that the scibert fine-tuned models are the default ones used in the Docker image.
